name: Hello World

on:
  push:
    branches:
      - laba2

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print message
        run: echo "Привет, GitHub Actions работает!"
